### ISSUE TITLE
The website domain is expired!

### ISSUE THREAD

**Issue by therajuahammad** [theanam/evileval#16]
![image](https://user-images.githubusercontent.com/25717712/99140691-2097a800-266e-11eb-80c5-76beb82b975d.png)

Vaiya, Maybe the domain is expired. If disconnect the GitHub page from domain redirects it will be live again.

Thank you.

**Comment by theanam** [comment]
yes I noticed. will update soon.

**Comment by therajuahammad** [comment]
okay vaiya. thanks
