### ISSUE TITLE
The website is not accessible

### ISSUE THREAD

**Issue by thenahidul** [theanam/evileval#9]
I cannot access "https://evileval.io/" website. 

<img width="1440" alt="screenshot 2019-01-26 at 5 48 51 pm" src="https://user-images.githubusercontent.com/16687953/51786733-aa713b00-2192-11e9-85b4-2b0a5d69ec0e.png">

**Comment by theanam** [comment]
For some reason Github SSL certificate is causing problem. I've contacted Github. Should get back to normal soon.

**Comment by theanam** [comment]
Fixed.

**Comment by thenahidul** [comment]
Great! Thanks.

**Comment by theshakilahmed** [comment]
The problem is still there for the https version
